version: '3.8'

services:
  ecosurprise-app:
    build: .
    container_name: ecosurprise-backend
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL:-jdbc:mysql://localhost:3306/ecosurprise?useSSL=false&serverTimezone=UTC}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-root}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-tu_password}
      JWT_SECRET: ${JWT_SECRET:-ecosurprise_secret_key_2024_secure_and_long_enough_for_hs512}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}
    ports:
      - "8080:8080"
    volumes:
      - app_uploads:/app/uploads
    network_mode: "host"

volumes:
  app_uploads:
    driver: local