version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: ecosurprise-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-Dev1045417325.}
      MYSQL_DATABASE: ${DB_NAME:-ecosurprise}
      MYSQL_USER: ${DB_USER:-ecosurprise_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-Dev1045417325.}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecosurprise-network
    deploy:
      resources:
        limits:
          memory: 300M
          cpus: "0.3"
    command: >
      --max-connections=40
      --innodb-buffer-pool-size=128M

  ecosurprise-app:
    build: .
    container_name: ecosurprise-backend
    restart: unless-stopped
    depends_on:
      - mysql-db
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-ecosurprise}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-Dev1045417325.}
      SERVER_PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: 3600000
      DATABASE_URL: jdbc:mysql://mysql-db:3306/${DB_NAME:-ecosurprise}?useSSL=false&serverTimezone=UTC
      DATABASE_USERNAME: ${DB_USER:-root}
      DATABASE_PASSWORD: ${DB_PASSWORD:-Dev1045417325.}
      JAVA_OPTS: "-Xmx192m -XX:MaxMetaspaceSize=64m"
    ports:
      - "8080:8080"
    networks:
      - ecosurprise-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.2"

volumes:
  mysql_data:

networks:
  ecosurprise-network:
