version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: ecosurprise-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-Dev1045417325.}
      MYSQL_DATABASE: ${DB_NAME:-ecosurprise}
      MYSQL_USER: ${DB_USER:-ecosurprise_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-Dev1045417325.}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecosurprise-networks
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  ecosurprise-app:
    build: .
    container_name: ecosurprise-backend
    restart: unless-stopped
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-ecosurprise}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-Dev1045417325.}
      SERVER_PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: 3600000
    ports:
      - "8080:8080"
    networks:
      - ecosurprise-network

volumes:
  mysql_data:

networks:
  ecosurprise-network: