version: '3.8'

services:
  ecosurprise-app:
    build: .
    container_name: ecosurprise-backend
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL:-jdbc:mysql://localhost:3306/ecosurprise?useSSL=false&serverTimezone=UTC}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-root}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-tu_password}
      APP_IP: ${APP_IP:-0.0.0.0}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    ports:
      - "8080:8080"
    volumes:
      - app_uploads:/app/uploads
    network_mode: "host"

volumes:
  app_uploads:
    driver: local