name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Make mvnw executable
      run: chmod +x ./mvnw
        
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Run tests
      run: ./mvnw test
      env:
        DATABASE_URL: jdbc:h2:mem:testdb 
        DATABASE_USERNAME: sa
        DATABASE_PASSWORD:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        SPRING_PROFILES_ACTIVE: test
        
  deploy:
    needs: test
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest  # ← Añadido
    if: github.ref == 'refs/heads/master'
    env:  # ← Variables movidas aquí
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      SVC_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Railway
      run: railway up --service=${{ env.SVC_ID }}  # ← Comando directo